/**
 * Refresh the "Watch It. Love It." section from Instagram.
 *
 * Usage: npm run fetch:reels
 *
 * Fetches the latest posts from instagram.com/woodhouseherbals, downloads
 * portrait covers for every reel into public/reels/ (Instagram CDN URLs are
 * signed and expire, so they must be stored locally), prunes covers for reels
 * that dropped out of the feed, and regenerates src/data/reels.ts.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const USERNAME = 'woodhouseherbals';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REELS_DIR = path.join(ROOT, 'public', 'reels');
const DATA_FILE = path.join(ROOT, 'src', 'data', 'reels.ts');

const HEADERS = {
  // Public web app id Instagram's own frontend sends; required for this endpoint.
  'x-ig-app-id': '936619743392459',
  'User-Agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
};

function cleanCaption(raw) {
  const stripped = raw.replace(/#\w+/g, '').trim();
  const first = stripped.split(/\n|(?<=[.!?…])\s/)[0] ?? '';
  return first.replace(/^[\s.-]+|[\s.-]+$/g, '').slice(0, 90);
}

const res = await fetch(
  `https://www.instagram.com/api/v1/users/web_profile_info/?username=${USERNAME}`,
  { headers: HEADERS },
);
if (!res.ok) {
  throw new Error(`Instagram responded ${res.status} — try again later or from a different network.`);
}
const json = await res.json();
const edges = json?.data?.user?.edge_owner_to_timeline_media?.edges ?? [];
const videos = edges.map((e) => e.node).filter((n) => n.is_video);
if (videos.length === 0) {
  throw new Error('No reels found in the feed — response shape may have changed, not overwriting anything.');
}

await mkdir(REELS_DIR, { recursive: true });
const reels = [];
for (const node of videos) {
  const url = node.thumbnail_tall_src || node.thumbnail_src || node.display_url;
  const img = await fetch(url, { headers: { 'User-Agent': HEADERS['User-Agent'] } });
  if (!img.ok) throw new Error(`Thumbnail download failed (${img.status}) for ${node.shortcode}`);
  await writeFile(path.join(REELS_DIR, `${node.shortcode}.jpg`), Buffer.from(await img.arrayBuffer()));
  const rawCaption = node.edge_media_to_caption?.edges?.[0]?.node?.text ?? '';
  reels.push({ shortcode: node.shortcode, caption: cleanCaption(rawCaption) });
  console.log(`✓ ${node.shortcode}  ${reels.at(-1).caption.slice(0, 60)}`);
}

// prune covers for reels no longer in the feed
const keep = new Set(reels.map((r) => `${r.shortcode}.jpg`));
for (const file of await readdir(REELS_DIR)) {
  if (!keep.has(file)) {
    await rm(path.join(REELS_DIR, file));
    console.log(`✗ pruned stale ${file}`);
  }
}

const entries = reels
  .map(
    (r) =>
      `  {\n    shortcode: '${r.shortcode}',\n    caption: '${r.caption.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',\n    thumbnail: '/reels/${r.shortcode}.jpg',\n  },`,
  )
  .join('\n');

await writeFile(
  DATA_FILE,
  `// Generated by \`npm run fetch:reels\` — do not edit entries by hand.
// Source: https://www.instagram.com/${USERNAME}/reels/
// Thumbnails are stored locally in /public/reels because Instagram CDN URLs
// are signed and expire.

export type Reel = {
  shortcode: string;
  caption: string;
  thumbnail: string;
};

export const INSTAGRAM_HANDLE = '${USERNAME}';
export const INSTAGRAM_URL = 'https://www.instagram.com/${USERNAME}/';

export function reelUrl(shortcode: string) {
  return \`https://www.instagram.com/reel/\${shortcode}/\`;
}

export function reelEmbedUrl(shortcode: string) {
  return \`https://www.instagram.com/reel/\${shortcode}/embed/\`;
}

export const reels: Reel[] = [
${entries}
];
`,
);
console.log(`\nWrote ${reels.length} reels to src/data/reels.ts`);
