// Generated by `npm run fetch:reels` — do not edit entries by hand.
// Source: https://www.instagram.com/woodhouseherbals/reels/
// Thumbnails are stored locally in /public/reels because Instagram CDN URLs
// are signed and expire.

export type Reel = {
  shortcode: string;
  caption: string;
  thumbnail: string;
};

export const INSTAGRAM_HANDLE = 'woodhouseherbals';
export const INSTAGRAM_URL = 'https://www.instagram.com/woodhouseherbals/';

export function reelUrl(shortcode: string) {
  return `https://www.instagram.com/reel/${shortcode}/`;
}

export function reelEmbedUrl(shortcode: string) {
  return `https://www.instagram.com/reel/${shortcode}/embed/`;
}

export const reels: Reel[] = [
  {
    shortcode: 'DZxE-hevbLq',
    caption: 'Jitsu trend but with all our skincare',
    thumbnail: '/reels/DZxE-hevbLq.jpg',
  },
  {
    shortcode: 'DZuB4LjyVqv',
    caption: 'Your skin called',
    thumbnail: '/reels/DZuB4LjyVqv.jpg',
  },
  {
    shortcode: 'DZetezMPJtY',
    caption: 'We spend hours taking care of everything else',
    thumbnail: '/reels/DZetezMPJtY.jpg',
  },
  {
    shortcode: 'DZRsBoYyFX8',
    caption: 'POV: You came to save money…',
    thumbnail: '/reels/DZRsBoYyFX8.jpg',
  },
  {
    shortcode: 'DZMXbTDSltF',
    caption: 'If you’re remembering your sunscreen only at the beach, this is your sign',
    thumbnail: '/reels/DZMXbTDSltF.jpg',
  },
  {
    shortcode: 'DZKx3nUyyYz',
    caption: 'POV: Your skin finally found a face wash that cleans without leaving it feeling dry',
    thumbnail: '/reels/DZKx3nUyyYz.jpg',
  },
  {
    shortcode: 'DZJts5syGbT',
    caption: 'Everything your skin needs, nothing it doesn’t',
    thumbnail: '/reels/DZJts5syGbT.jpg',
  },
  {
    shortcode: 'DZIEm-9yzcw',
    caption: 'That one friend who always reminds everyone to carry sunscreen?',
    thumbnail: '/reels/DZIEm-9yzcw.jpg',
  },
  {
    shortcode: 'DZHU3nvyZpx',
    caption: 'Your hand is full, but somehow you’re still carrying everyone’s essentials',
    thumbnail: '/reels/DZHU3nvyZpx.jpg',
  },
  {
    shortcode: 'DZFXiQEyj1q',
    caption: 'That “Oh wow!” moment when every product in the pouch is exactly what you wanted',
    thumbnail: '/reels/DZFXiQEyj1q.jpg',
  },
  {
    shortcode: 'DZEoKHNSPDh',
    caption: 'When someone asks how much I love my skincare routine',
    thumbnail: '/reels/DZEoKHNSPDh.jpg',
  },
];
